[package]
name = "lns-vrp-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = { version = "0.8.8", default-features = false }
bumpalo = { version = "3.15.0", features = ["allocator_api"] }
core = { package = "lns-vrp-core", path = "../core" }
geo = "0.27.0"
geojson = "0.24.1"
itertools = "0.12.1"
ordered-float = "4.2.0"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"

[dev-dependencies]
criterion = "0.5.1"
insta = "1.35.1"
pretty_assertions = "1.4.0"

[features]
trace = []

[[bench]]
name = "main"
harness = false
