[package]
name = "lns-vrp-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = { version = "0.8.11", default-features = false }
bumpalo = { version = "3.16.0", features = ["allocator_api"] }
core = { package = "lns-vrp-core", path = "../core" }
geo = "0.28.0"
geojson = "0.24.1"
itertools = "0.13.0"
ordered-float = "4.4.0"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[dev-dependencies]
criterion = "0.5.1"
insta = "1.40.0"
pretty_assertions = "1.4.1"

[features]
trace = []

[[bench]]
name = "main"
harness = false

[lints]
workspace = true
