[package]
name = "vrp"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = "0.26.0"
im-rc = "15.1.0"
ordered-float = "3.9.1"

[dev-dependencies]
criterion = "0.5.1"
pretty_assertions = "1.4.0"
rand = "0.8.5"

[[bench]]
name = "main"
harness = false
