[package]
name = "vrp"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.3"
geo = "0.26.0"
ordered-float = "3.9.1"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.5.1"
pretty_assertions = "1.4.0"

[[bin]]
name = "vrp"

[[bench]]
name = "main"
harness = false
