[package]
name = "lns-vrp-core"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = "0.28.0"
ordered-float = "4.4.0"
serde = { version = "1.0.210", features = ["derive"] }

[lints]
workspace = true
