[package]
name = "lns-vrp-core"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = "0.26.0"
geojson = "0.24.1"
ordered-float = "4.1.1"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
