[package]
name = "lns-vrp-core"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = "0.29.3"
ordered-float = "5.0.0"
serde = { version = "1.0.217", features = ["derive"] }

[lints]
workspace = true
